### ISSUE TITLE
GCTools Elgg plugins that overlap with GCColab

### ISSUE THREAD

**Issue by chown-your-poptarts** [gctools-hackathon-ircc/gccollab#1]
Extracted GC Connex plugins in GC Collab
- [x] b_extended_profile
- [x] gc_api
- [x] gc_group_deletion
- [x] GC_profileStrength
- [x] GoC_dev_banner
- [x] ideas
- [x] missions
- [x] missions_organization
- [x] missions_profile_extend
- [x] toggle_language
- [x] unvalidated_user_cleanup
- [x] wet4
- [x] achievement_badges
- [x] cp_notifications
- [x] custom_error_page
- [x] c_email_extensions
- [x] c_members_byDepartment
- [x] c_module_dump
- [ ] ~c_notification_messages~
- [x] gcforums
- [x] gcProfilePicturesBadges
- [x] gcRegistration 
- [x] widget_manager_accessibility

Gccolab plugins not extracted:
**Note:** This is a first pass at both lists, this portion will not be 100% accurate.
~achievement_badges~
apiadmin
b_extended_profile_collab
contactform?
gcRegistration_collab
gcRegistration_invitation
gc_autosubscribegroup
gc_fedsearch_gsa
gc_group_layout
gc_landing_pages
gc_newsfeed
gc_official_groups
gc_onboard
gc_splash_page
gc_splash_page_collab
gc_streaming_content
gccollab_stats
gccollab_theme
gcconnex_theme
geds_sync
groups
saml_link

third party pluigns modified:
elgg_recaptcha
elgg_solr
embed_extender
event_calendar
file_tools
friend_request
group_operators
group_tools
login_as
loginrequired
machine_translation
maintenance
messageboard
mt_activity_tabs
multi_file_upload
notifications_languages
oauth_api
phpmailer
polls
rename_friends
simplesaml
sphinx
tasks
thewire_tools
translation_editor
twitter
vroom

**Comment by nschonni** [comment]
- wet4
- b_extendend_profile
- c_email_extensions (my just be behind)
- c_members_byDepartment
- c_module_dump (maybe just behind)
- cp_notifications
- gc_api
- GC_profileStrength
- gcRegistration
- missions
- missions_profile_extend

**Comment by nschonni** [comment]
Moved upstream https://github.com/gctools-outilsgc/gccollab/issues/115
